StoreOrderingDashBoard/Controllers/DCManagerController.cs
using BAL;
using DAL;
using DbLayer.Service;
using StoreOrderingDashBoard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace StoreOrderingDashBoard.Controllers
{
    [AdminAuthorization]
    public class DCManagerController : Controller
    {
        //tested SVN Tested
        private readonly ICustomerService _customerService;
        private readonly ILocationService _locationService;
        private readonly IUserService _userService;
        private readonly IMenuService _menuService;
        private readonly IStoreService _storeService;
        private readonly IAuditService _auditService;

        public DCManagerController(ICustomerService customerService, ILocationService locationService, IUserService userService, IMenuService menuService, IStoreService storeService, IAuditService auditService)
        {
            _customerService = customerService;
            _locationService = locationService;
            _userService = userService;
            _menuService = menuService;
            _storeService = storeService;
            _auditService = auditService;
        }

        public ActionResult AddDcManager()
        {
            ViewBag.Companies = _customerService.GetCompanies();
            ViewBag.CustomerPlan = _customerService.GetCustomerPlans();
            return View();
        }
        // GET: DCManager
        public ActionResult Index()
        {
            ViewBag.AdminUsers = _userService.GetAdminUsers();
            return View();
        }
        //      [AdminAuthorization]
        public ActionResult AddAdminUser()
        {
            List<Locations> locations = _locationService.GetAllLocations();
            List<Company> companies = _customerService.GetCompanies();
            List<CustomerPlan> plans = _customerService.GetCustomerPlans();
            List<String> Departments = _userService.GetDepartments();
            List<AllQuestion> allQuestions = _customerService.allQuestions();
            List<Customer> customers = _customerService.GetAllCustomers();
            //List<Role> Roles = _userService.GetRoles();
            Users users = new Users();            
            users.RoleId = 2;
            List<SelectListItem> SelectLocations = locations.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Name,
                    Value = a.LocationId.ToString(),
                    Selected = false
                };
            });
            List<SelectListItem> SelectCustomers = customers.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Name,
                    Value = a.Id.ToString(),
                    Selected = false
                };
            });
            ViewBag.Locations = SelectLocations;
            ViewBag.Customers = SelectCustomers;
            ViewBag.Companies = companies;
            ViewBag.Plans = plans;
            ViewBag.Departments = Departments;
            ViewBag.Questions = allQuestions;
            users.AllQuestions = allQuestions;
            //users.
            users.Customers = customers;
            //ViewBag.Roles = Roles;
            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAdminUser(Users user)
        {
            //var JavaScriptSerializer = new JavaScriptSerializer();
            //List<JsonStore> stores = JavaScriptSerializer.Deserialize<List<JsonStore>>(user.Stored);
            if (ModelState.IsValid)
            {
                var Users = _userService.GetUsersByEmail(user.EmailAddress);
                if (Users != null)
                {
                    List<Locations> locations = _locationService.GetAllLocations();
                    List<Company> companies = _customerService.GetCompanies();
                    List<CustomerPlan> plans = _customerService.GetCustomerPlans();
                    List<String> Departments = _userService.GetDepartments();
                    List<AllQuestion> allQuestions = _customerService.allQuestions();
                    List<Customer> customers = _customerService.GetAllCustomers();
                    user.RoleId = 2;

                    List<SelectListItem> SelectLocations = locations.ConvertAll(a =>
                    {
                        return new SelectListItem()
                        {
                            Text = a.Name,
                            Value = a.LocationId.ToString(),
                            Selected = user.Locations.LocationId == a.LocationId ? true : false
                        };
                    });
                    List<SelectListItem> SelectCustomers = customers.ConvertAll(a =>
                    {
                        return new SelectListItem()
                        {
                            Text = a.Name,
                            Value = a.Id.ToString(),
                            Selected = user.Customer.Contains(a.Id) ? true : false
                        };
                    });
                    ViewBag.Locations = SelectLocations;
                    ViewBag.Companies = companies;
                    ViewBag.Plans = plans;
                    ViewBag.Departments = Departments;
                    ViewBag.Questions = allQuestions;
                    ViewBag.Customers = SelectCustomers;
                    user.AllQuestions = allQuestions;
                    user.Customers = customers;
                    ModelState.AddModelError("EmailAddress", "Email Address is Already Exist");
                    return View(user);
                }
                else
                {
                    user.IsDeleted = false;
                    user.CreatedOn = DateTime.Now;
                    user.ReportToId = 1;
                    user.RoleId = 2;
                    user.CreatedBy = SessionValues.UserId;
                    var userid = _userService.AddAdminUser(user);
                    foreach (AllQuestion allQuestion in user.AllQuestions)
                    {
                        Answer answer = new Answer();
                        answer.Id = allQuestion.Id;
                        answer.Answers = allQuestion.answer;
                        answer.Users = new Users();
                        answer.Users.Id = userid;
                        _userService.InsertAnswer(answer);
                        try
                        {
                            var auditJavascript = new JavaScriptSerializer();
                            var answerAudit = auditJavascript.Serialize(answer);
                            _auditService.InsertAudit(HelperCls.GetIPAddress(), answerAudit, Request.Url.OriginalString.ToString(), SessionValues.UserId, null);
                        }
                        catch (Exception ex)
                        {
                            HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                            throw ex;
                        }
                    }

                    if (user.Stored != null && user.Stored != "")
                    {
                        var JavaScriptSerializer = new JavaScriptSerializer();
                        List<JsonStore> stores = JavaScriptSerializer.Deserialize<List<JsonStore>>(user.Stored);
                        string[] store = user.Stored.Split(',');
                        foreach (JsonStore jsonstore in stores)
                        {
                            PermitableCls permitable = new PermitableCls();
                            permitable.Users = new Users();
                            permitable.CreatedBy = (int)user.CreatedBy;
                            //permitable.CreatedOn=
                            permitable.Users.Id = userid;
                            permitable.Customer = new Customer();
                            permitable.StoreId = Convert.ToInt32(jsonstore.StoreId);
                            _userService.InsertPermitable(permitable);
                            try
                            {
                                var auditJavascript = new JavaScriptSerializer();
                                var permitableAudit = auditJavascript.Serialize(permitable);
                                _auditService.InsertAudit(HelperCls.GetIPAddress(), permitableAudit, Request.Url.OriginalString.ToString(), SessionValues.UserId, null);
                            }
                            catch (Exception ex)
                            {
                                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                                throw ex;
                            }
                        }
                        foreach (int customer in user.Customer)
                        {
                            if (!(stores.Any(x => x.CustId == customer)))
                            {
                                PermitableCls permitable = new PermitableCls();
                                permitable.CreatedBy = (int)user.CreatedBy;
                                //permitable.CreatedOn=
                                permitable.Users = new Users();
                                permitable.Users.Id = userid;
                                permitable.Customer = new Customer();
                                permitable.Customer.Id = customer;
                                _userService.InsertPermitable(permitable);
                                try
                                {
                                    var auditJavascript = new JavaScriptSerializer();
                                    var permitableAudit = auditJavascript.Serialize(permitable);

StoreOrderingDashBoard/Views/DCManager/AddDcManager.cshtml
@model DAL.Users
@{
    ViewBag.Title = "AddDcManager";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>Add Dc Manager</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Dc Manager<small> Form</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" action="@Url.Action("AddDcManager","DCManager")" method="post">
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Name">
                                    DcManager Name <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="Name" required="required" name="Name" class="form-control col-md-7 col-xs-12" value="@Model.Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="EmailAddress">
                                    Email Address <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="EmailAddress" required="required" name="EmailAddress" class="form-control col-md-7 col-xs-12" value="@Model.EmailAddress">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Password">
                                    Password <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="Password" required="required" name="Password" class="form-control col-md-7 col-xs-12" value="@Model.Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ConfirmPassword">
                                    Confirm Password <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="ConfirmPassword" required="required" name="ConfirmPassword" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="store-location">
                                    Location <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @*<input type="text" id="store-location" required="required" name="Location" class="form-control col-md-7 col-xs-12" value="@Model.Locations">*@
                                    @(Html.DropDownList("LocationId", new SelectList(ViewBag.LocationList, "Id", "Name", Model.LocationId), "--Choose Location---", new { @class = "form-control col-md-7 col-xs-12", required = "required" }))
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="store-location">
                                    Company <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @*<input type="text" id="store-location" required="required" name="Location" class="form-control col-md-7 col-xs-12" value="@Model.Locations">*@
                                    @(Html.DropDownList("Company.Id", new SelectList(ViewBag.LocationList, "Id", "Name", Model.Company.Id), "--Choose Company---", new { @class = "form-control col-md-7 col-xs-12", required = "required" }))
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="store-custId">
                                    Customer Plan <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @*<input type="text" id="store-custId" required="required" name="CustId" class="" value="">*@
                                    @(Html.DropDownList("CustomerPlan.Id", new SelectList(ViewBag.CustomerList, "Id", "PlanName", Model.CustomerPlan.Id), "--Choose Plan---", new { @class = "form-control col-md-7 col-xs-12", required = "required" }))
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    @*<button class="btn btn-primary" type="reset">Reset</button>*@
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StoreOrderingDashBoard/Views/DCManager/Index.cshtml
@using DAL;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>Admin Users @*<small>Some examples to get you started</small>*@</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        @*<h2>Default Example <small>Users</small></h2>*@
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="loader"></div>
                    <div class="x_content">

                        <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline" role="grid" aria-describedby="datatable_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="UserId: activate to sort column descending">UserId</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="User Name: activate to sort column ascending">User Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Edit: activate to sort column ascending">Edit</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Plans: activate to sort column ascending">Plans</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Widgets: activate to sort column ascending">Widgets</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Delete: activate to sort column ascending">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.AdminUsers != null)
                                {
                                    int sr = 1;
                                    foreach (DcAdmin user in ViewBag.AdminUsers)
                                    {
                                        <tr role="row" class="@(sr%2!=0?"Odd":"even")">
                                            <td>
                                                @user.Id
                                            </td>
                                            <td>
                                                @user.Name
                                            </td>
                                            <td>
                                                <a class="btn btn-primary datatable-btn" href="@Url.Action("EditAdminUser","DCManager",new { UserId=user.Id})">Edit</a>
                                            </td>
                                            <td>
                                                <button class="btn btn-info datatable-btn" type="button" onclick="View(@user.PlanId,@user.Id);" value="@user.PlanId">Plans</button>
                                            </td>
                                            <td>
                                                <button class="btn btn-warning datatable-btn" type="button" onclick="Widgets(@user.PlanId,@user.Id);" value="@user.PlanId">Widgets</button>
                                            </td>
                                            <td>
                                                <button class="btn btn-danger datatable-btn" type="button" onclick="Delete(@user.Id);" value="@user.Id">Delete</button>
                                            </td>
                                        </tr>
                                        sr++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="Custom_Plan_Model" role="dialog">
                <div class="modal-dialog modal-lg">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Customise Plan</h4>
                        </div>
                        <div class="modal-body">
                            <div id="partial"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" onclick="Create()" data-dismiss="modal">Save</button>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal fade" id="Custom_Widget_Model" role="dialog">
                <div class="modal-dialog modal-lg">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Role Management <small>Widget</small></h4>
                        </div>
                        <div class="modal-body">
                            <div id="Partial_Widgets"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" onclick="RoleCreate()" data-dismiss="modal">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".loader").hide();
    });
    function Delete(Id) {
            //$('.loader').show();
                //OpenAutoModel("Approval");
        var a = confirm("Are you sure want to delete User?");
        if (a) {
            $(".loader").show();
            $.ajax({
                url: '@Url.Action("DeleteAdminUser", "DCManager")',
                type: "post",
                datatype: "json",
                data: {
                    "UserId": Id
                },
                success: function (response) {
                    if (response == "true" || response == true) {
                        location.reload();
                    }
                },
            })
        }
    }
    function View(CustomerPlanId, UserId) {
        var drop = CustomerPlanId;
        if (!isNaN(drop)) {
            $('#partial').load();
            $("#Custom_Plan_Model").modal('show');
            var route = '@Url.Action("MenuRightsForUser", "DCManager")?UserId=' + UserId + '&custplanid=' + drop + '';
            $('#partial').load(route);
        }
        else {
            $("#Custom_Plan_Model").modal('hide');
            alert("Please select plan")
        }
    }
    function Widgets(CustomerPlanId, UserId) {
        var drop = CustomerPlanId;
        if (!isNaN(drop)) {
            $('#Partial_Widgets').load();
            $("#Custom_Widget_Model").modal('show');
            var route = '@Url.Action("WidgetsForUser", "DCManager")?UserId=' + UserId + '&custplanid=' + drop + '';
            $('#Partial_Widgets').load(route);
        }
        else {
            $("#Custom_Widget_Model").modal('hide');
            alert("Please select plan")
        }
    }
</script>

StoreOrderingDashBoard/Views/DCManager/_MenuRights.cshtml
@using DAL
@{ 
    int admin=Convert.ToInt32(ViewData["AdminID"].ToString());
    int custplanid = Convert.ToInt32(ViewData["CustPlanId"].ToString());
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Item List</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="example" class="table table-striped table-bordered table-responsive">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>MenuId</td>
                        <th>Menu</th>
                        <th>Show</th>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.Menu != null)
                    {
                        int i = 1;
                        foreach (Menu role in ViewBag.Menu)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@role.Id</td>
                                <td>@role.MenuName</td>
                                @if (role.PlanId > 0)
                                {
                                    <td><input type="checkbox" id="@("Check"+i)" value="@role.PlanId" name="id[]" @*onclick="Create(@role.PlanId,@role.Id)"*@ checked /></td>
                                }
                                else
                                {
                                    <td><input type="checkbox" id="@("Check"+i)" value="@role.PlanId" name="id[]" @*onclick="Create(@role.PlanId,@role.Id)"*@ /></td>
                                }

                            </tr>
                            i++;
                        }
                    }


                </tbody>

            </table>

            <div class="loader"></div>
        </div>
    </div>
    <script>
        var t;
        var productlist = [];
        var menu = [];
        $(document).ready(function () {
            $(".loader").hide();
            t = $('#example').DataTable();
        });
function Create() {
        debugger;
        $(".loader").show();
        var tableinfo = t.page.info();
        total = tableinfo.recordsTotal
    var userid =@admin;
    var custplanid=@custplanid;
        for (i = 0; i < total; i++) {
            var data = t.$('input[id=Check' + (i+1) + '], checked').serialize();
            var data1 = t.cell(i, 3).nodes().to$().find('input').val()
                var da = t.row(i).data();
                var product = {};
                product.PlanId =data!=""?parseInt(data1):null;
            product.Id = parseInt(da[1]);
            product.IsShow = data != "" ? true : false;
            menu.push(product);
        }

         var r = confirm("Are you Sure Want to Save?");
        if (r) {
            $.ajax({
                url: "@Url.Action("SaveMenuManagement", "DCManager")",
                type: "POST",
                data: {
                    "menus": menu,
                    "UserId": userid,
                    "CustPlanId": custplanid
                },
                success: function (response) {
                    if (response) {
                        $(".loader").hide();
                        alert("Menu Management Saved Successfully");
                        // window.location=@Url.Action("Index", "DCManager");
                        location.reload();
                    }
                }
            });
        }
        else {
            $(".loader").hide();
        }
    }
    </script>
</div>