StoreOrderingDashBoard/Controllers/WareHouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DbLayer.Service;
using DAL;
using StoreOrderingDashBoard.Models;
using System.Web.Script.Serialization;
using BAL;

namespace StoreOrderingDashBoard.Controllers
{
    public class WareHouseController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IWareHouseService _wareHouseService;
        private readonly ILocationService _locationService;
        private readonly IAuditService _auditService;
        public WareHouseController(ICustomerService customerService, IWareHouseService wareHouseService, ILocationService locationService, IAuditService auditService)
        {
            _customerService = customerService;
            _wareHouseService = wareHouseService;
            _locationService = locationService;
            _auditService = auditService;
        }
        // GET: WareHouse
        [AdminAuthorization]
        public ActionResult Index()
        {
            ViewBag.WareHouseDcs = _wareHouseService.wareHouseDCs();
            return View();
        }

        [AdminAuthorization]
        public ActionResult AddWarehouse()
        {
            ViewBag.Companies = _customerService.GetCompanies();
            ViewBag.Location = _locationService.GetAllLocations();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorization]
        public ActionResult AddWarehouse(WareHouseDC wareHouseDC)
        {
            wareHouseDC.Company = _wareHouseService.Company(wareHouseDC.Company.Id);
            wareHouseDC.CreatedOn = DateTime.Now;
            var affected = _wareHouseService.InsertWareHouse(wareHouseDC);
            if (affected > 0)
            {
                try
                {
                    var auditJavascript = new JavaScriptSerializer();
                    var WareHouse = new WareHouseDC(wareHouseDC.Id, wareHouseDC.Name, wareHouseDC.LocationId, wareHouseDC.Company.Id, wareHouseDC.PermitableCls, wareHouseDC.Stores);
                    var WareHouseAudit = auditJavascript.Serialize(WareHouse);
                    _auditService.InsertAudit(HelperCls.GetIPAddress(), WareHouseAudit, Request.Url.OriginalString.ToString(), SessionValues.UserId, null);
                }
                catch (Exception ex)
                {
                    HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                    throw ex;
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        [AdminAuthorization]
        public ActionResult EditWareHouse(int Id)
        {
            var warehouse = _wareHouseService.WareHouseDC(Id);
            ViewBag.Companies = _customerService.GetCompanies();
            ViewBag.Location = _locationService.GetAllLocations();
            return View(warehouse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthorization]
        public ActionResult EditWareHouse(WareHouseDC wareHouseDC)
        {
            var affected = _wareHouseService.UpdateWareHouse(wareHouseDC);
            if (affected > 0)
            {
                try
                {
                    var auditJavascript = new JavaScriptSerializer();
                    var WareHouse = new WareHouseDC(wareHouseDC.Id, wareHouseDC.Name, wareHouseDC.LocationId, wareHouseDC.Company.Id, wareHouseDC.PermitableCls, wareHouseDC.Stores);
                    var WareHouseAudit = auditJavascript.Serialize(WareHouse);
                    _auditService.InsertAudit(HelperCls.GetIPAddress(), WareHouseAudit, Request.Url.OriginalString.ToString(), SessionValues.UserId, null);
                }
                catch (Exception ex)
                {
                    HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                    throw ex;
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        [AdminApiAuthorization]
        public JsonResult DeleteWareHouse(int Id)
        {
            bool cond = _wareHouseService.DeleteWareHouse(Id) > 0 ? true : false;
            try
            {
                var auditJavascript = new JavaScriptSerializer();
                var WareHouseAudit = auditJavascript.Serialize("wareHouseDCId: " + Id + ", IsDeleted:" + cond);
                _auditService.InsertAudit(HelperCls.GetIPAddress(), WareHouseAudit, Request.Url.OriginalString.ToString(), SessionValues.UserId, null);
            }
            catch (Exception ex)
            {
                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                throw ex;
            }
            return Json(cond, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetWareHouses()
        {
            int LoggedInUserId = SessionValues.UserId;
            int LoggedInCustomer = Convert.ToInt32(SessionValues.LoggedInCustId);
            List<WareHouseDCView> dCs = _wareHouseService.GetWareHouseForCustomerId(LoggedInUserId, LoggedInCustomer, "Report");
            return Json(new { data = dCs }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetWareHousesStoreItem()
        {
            int LoggedInUserId = SessionValues.UserId;
            int LoggedInCustomer = Convert.ToInt32(SessionValues.LoggedInCustId);
            List<WareHouseDCView2> dCs = _wareHouseService.GetWareHousesStoreItem(LoggedInUserId, LoggedInCustomer);
            return Json(new { data = dCs }, JsonRequestBehavior.AllowGet);
        }
    }
}

StoreOrderingDashBoard/Views/WareHouse/AddWarehouse.cshtml
@using DAL
@{
    ViewBag.Title = "AddWarehouse";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>Add WareHouse</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Customer<small> Form</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" action="@Url.Action("AddWarehouse","WareHouse")" method="post">
                            @Html.AntiForgeryToken()

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Name">
                                    Name <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="Name" required="required" name="Name" class="form-control col-md-7 col-xs-12" value="">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Company.Id">
                                    Company <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">

                                    <select required="required" name="Company.Id" class="form-control col-md-7 col-xs-12">
                                        <option value="">Select Company Name</option>
                                        @if (ViewBag.Companies != null)
                                        {
                                            foreach (Company com in ViewBag.Companies)
                                            {
                                                <option value="@com.Id">@com.Name</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="LocationId">
                                    Location <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">

                                    <select required="required" name="LocationId" class="form-control col-md-7 col-xs-12">
                                        <option value="">Select Location Name</option>
                                        @if (ViewBag.Location != null)
                                        {
                                            foreach (Locations plan in ViewBag.Location)
                                            {
                                                <option value="@plan.LocationId">@plan.Name</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-primary" type="reset">Reset</button>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StoreOrderingDashBoard/Views/WareHouse/EditWareHouse.cshtml
@model DAL.WareHouseDC
@using DAL
@{
    ViewBag.Title = "EditWareHouse";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>Add Customer</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>WareHouse<small> Form</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" action="@Url.Action("EditWareHouse","WareHouse")" method="post">
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                    Customer Name <span class="required">*</span>
                                </label>
                                <input type="hidden" name="Id" value="@Model.Id" />
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="first-name" required="required" name="Name" class="form-control col-md-7 col-xs-12" value="@Model.Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                    Company Name <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">

                                    <select required="required" name="Company.Id" class="form-control col-md-7 col-xs-12">
                                        <option value="">Select Company Name</option>
                                        @if (ViewBag.Companies != null)
                                        {
                                            foreach (Company com in ViewBag.Companies)
                                            {
                                                if (Model.Company.Id == com.Id)
                                                {
                                                    <option value="@com.Id" selected>@com.Name</option>
                                                }
                                                else
                                                {
                                                    <option value="@com.Id">@com.Name</option>
                                                }

                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                                    Location <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @(Html.DropDownList("LocationId", new SelectList(ViewBag.Location, "LocationId", "Name", Model.LocationId), "--Choose Location---", new { @class = "form-control col-md-7 col-xs-12", required = "required" }))
                                    @*<select required="required" name="CustomerPlan.Id" class="form-control col-md-7 col-xs-12">
                                        <option value="">Select Customer Plan</option>
                                        @if (ViewBag.CustomerPlan != null)
                                        {
                                            foreach (Locations plan in ViewBag.CustomerPlan)
                                            {
                                                if (Model.LocationId == ((null)plan.Id))
                                                                            {
                                                    <option value="@plan.LocationId" selected>@plan.Name</option>
                                                }
                                                                            else
                                                                            {
                                                    <option value="@plan.Id">@plan.PlanName</option>
                                                }

                                            }
                                        }
                                    </select>*@
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-primary" type="reset">Reset</button>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StoreOrderingDashBoard/Views/WareHouse/Index.cshtml
@using DAL
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>WareHouse</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        @*<h2>Default Example <small>Users</small></h2>*@
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="loader"></div>
                    <div class="x_content">
                        @*<p class="text-muted font-13 m-b-30">
                                DataTables has most features enabled by default, so all you need to do to use it with your own tables is to call the construction function: <code>$().DataTable();</code>
                            </p>*@
                        <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline" role="grid" aria-describedby="datatable_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 157px;">Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 117px;">Edit</th>
                                    <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 60px;">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.WareHouseDcs != null)
                                {
                                    int sr = 1;
                                    foreach (WareHouseDC ob in ViewBag.WareHouseDcs)
                                    {
                                        <tr role="row" class="@(sr%2!=0?"Odd":"even")">
                                            <td>
                                                @ob.Name
                                            </td>
                                            <td>
                                                <a class="btn btn-success datatable-btn" href="@Url.Action("EditWareHouse","WareHouse",new { Id=ob.Id})">Edit</a>
                                            </td>
                                            <td>
                                                <button class="btn btn-danger datatable-btn" type="button" onclick="Delete(@ob.Id);" value="@ob.Id">Delete</button>
                                            </td>
                                        </tr>
                                        sr++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".loader").hide();
    });
    function Delete(Id) {
          
            //$('.loader').show();
                //OpenAutoModel("Approval");
        var a = confirm("Are you sure want to delete WareHouse?");
        if (a) {
            $(".loader").show();
                $.ajax({
                    url: '@Url.Action("DeleteWareHouse", "WareHouse")',
                    type: "post",
                    datatype: "json",
                    data: {
                        "Id": Id
                    },
                    success: function (response) {
                        //debugger;
                        if (response == "true" || response==true) {
                            //OpenModel("Send Approval", "Response Sent!");
                            location.reload();
                            //$("#alert").css("Display", "Block");
                            //$(".borderUp").css("Display", "None");
                            //$(".borderUp :input").prop("disabled", true);
                        }
                    },
                })
        }

                   }
</script>