StoreOrderingDashBoard/Controllers/InvoiceController.cs
using BAL;
using DAL;
using DbLayer.Service;
using StoreOrderingDashBoard.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace StoreOrderingDashBoard.Controllers
{

    public class InvoiceController : Controller
    {
        private readonly IAuditService _auditService;
        private readonly IWareHouseService _wareHouseService;
        private readonly IOrderService _orderService;
        private readonly IStoreService _storeService;
        private readonly IItemService _itemService;
        private readonly IUserService _userService;

        public InvoiceController(IAuditService AuditService, IWareHouseService wareHouseService, IOrderService orderservice, IStoreService storeService, IItemService itemService, IUserService userService)
        {
            _auditService = AuditService;
            _wareHouseService = wareHouseService;
            _orderService = orderservice;
            _storeService = storeService;
            _itemService = itemService;
            _userService = userService;
        }

        [AdminAuthorization]
        public ActionResult AddDisptchedInformation()
        {
            //var warehouses = _wareHouseService.wareHouseDCs();
            int userid = SessionValues.UserId;
            int custid = Convert.ToInt32(SessionValues.LoggedInCustId);
            List<string> warehouses = _orderService.GetDistinctLocationsFromInvoice(userid, custid);
            //SelectList warehouse = new SelectList(warehouses.Select(x => new { Value = x, Text = x }), "Value", "Text");
            //ViewBag.WareHouse = warehouses;
            return View(warehouses);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminApiAuthorization]
        public ActionResult GetInvoicesforDateDC(DateTime InvoiceDate, string SelectedDCs)
        {
            try
            {
                List<InvoiceHeader> invoiceHeaders = _orderService.GetInvoicesforDateDC(InvoiceDate, SelectedDCs);
                //return Json(data: invoiceHeaders, behavior: JsonRequestBehavior.AllowGet);
                return Json(new { data = invoiceHeaders }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveDisptchInformation(List<InvoiceDispatch> DisptchInformation)
        {
            try
            {
                int userid = SessionValues.UserId;
                if (DisptchInformation != null && DisptchInformation.Count() > 0)
                {
                    //string empiDS = "";
                    foreach (InvoiceDispatch invoice in DisptchInformation)
                    {
                        if (string.IsNullOrEmpty(invoice.InvoiceNo) || string.IsNullOrEmpty(invoice.VehicleNo))
                        {
                            return Json("Unsuccessful");
                        }
                    }
                    foreach (InvoiceDispatch invoice in DisptchInformation)
                    {
                        InvoiceDispatch invoiceDispatch = new InvoiceDispatch
                        {
                            CreatedBy = userid,
                            InvoiceNo = invoice.InvoiceNo,
                            VehicleNo = invoice.VehicleNo,
                            CreatedDate = DateTime.Now
                        };
                        //invoiceDispatch.DispatchDate=invoice.DispatchDate;                        
                        long SheetId = _orderService.AddInvoiceDispatch(invoiceDispatch);
                        if (SheetId == 0)
                            return Json("Unsuccessful");
                    }

                    return Json("Successful");
                }
                else
                {
                    return Json("Unsuccessful");
                }
            }
            catch (Exception ex)
            {
                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                return Json("Unsuccessful");
            }
        }

        [HttpGet]
        [AdminAuthorization]
        public ActionResult PODForm()
        {
            int userid = SessionValues.UserId;
            int custid = Convert.ToInt32(SessionValues.LoggedInCustId);
            List<Store> ActiveStores = _storeService.GetStoresByCustomerId(custid);
            return View(ActiveStores);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminApiAuthorization]
        public ActionResult GetItemsforCustomer()
        {
            try
            {
                int custid = Convert.ToInt32(SessionValues.LoggedInCustId);
                List<Item> customeritems = _itemService.GetItemsForCustomer(custid);
                return Json(new { data = customeritems }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
                throw;
            }
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[AdminApiAuthorization]
        //public ActionResult SavePODInformation(string InvoiceNo, DateTime poddate, string Stores,List<PODResponse> response)
        //{
        //    bool cond = false;
        //    try
        //    {
        //        if (response.Count() > 0 && InvoiceNo != "" && InvoiceNo != null&&Stores!=""&&Stores!=null)
        //        {

        //            var PODHeader = new PODHeader();                    
        //            int userid = SessionValues.UserId;
        //            PODHeader.Invoice_Number = InvoiceNo;
        //            PODHeader.CreatedBy = userid;
        //            PODHeader.PODDate = poddate;
        //            PODHeader.CompanyId = _userService.GetCompanyAssigned(userid);

        //            long pk_PODHeader = _orderService.savePODResponse(PODHeader);
        //            try
        //            {
        //                var orderHeaderAudit = new PODHeader(pk_PODHeader, PODHeader.Invoice_Number, PODHeader.PODDate, PODHeader.CreatedBy);
        //                var auditJavascript = new JavaScriptSerializer();
        //                var OrderAudit = auditJavascript.Serialize(orderHeaderAudit);
        //                _auditService.InsertAudit(HelperCls.GetIPAddress(), OrderAudit, Request.Url.OriginalString.ToString(), userid, null);
        //            }
        //            catch (Exception ex)
        //            {
        //                HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
        //                throw ex;
        //            }
        //            foreach (PODResponse save in response.ToList())
        //            {
        //                PODDetail PODDetail = new PODDetail();
        //                PODDetail.Item = save.Item;
        //                PODDetail.ItemId = save.ItemId;
        //                PODDetail.InvoiceQuantity = save.InvoiceQty;
        //                PODDetail.DeliveredQuantity = save.DeliveredQty;
        //                PODDetail.PODHeaderId = pk_PODHeader;
        //                long pk_orderDetail = _orderService.savePODDetailResponse(PODDetail);
        //                try
        //                {
        //                    var OrderDetailAudit = new PODDetail(pk_orderDetail, PODDetail.InvoiceQuantity, PODDetail.DeliveredQuantity, PODDetail.PODHeaderId);
        //                    var auditJavascript = new JavaScriptSerializer();
        //                    var OrderAudit = auditJavascript.Serialize(OrderDetailAudit);
        //                    _auditService.InsertAudit(HelperCls.GetIPAddress(), OrderAudit, Request.Url.OriginalString.ToString(), userid, null);
        //                }
        //                catch (Exception ex)
        //                {
        //                    HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
        //                    throw ex;
        //                }
        //            }
        //            cond = (pk_PODHeader > 0 ? true : false);
        //            if (cond)
        //            {
        //                List<PODDetail> orderDetails = _orderService.GetPODDetails(pk_PODHeader);
        //                cond = (orderDetails.Count() > 0 ? true : false);
        //                if (!cond)
        //                    _orderService.DeletePODHeader(pk_PODHeader, userid);
        //            }
        //            //if (cond)
        //            //{
        //            //   HelperCls.SendEmail(store.StoreEmailId, "Order Finalize", HelperCls.PopulateBodyFinalizeorder(store.StoreName, pk_PODHeader.ToString()));
        //            //}
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        HelperCls.DebugLog(ex.Message + System.Environment.NewLine + ex.StackTrace);
        //    }
        //    return Json(cond, JsonRequestBehavior.AllowGet);
        //}

        public ActionResult AddDAForVehicle()
        {
            return View();
        }
        public ActionResult LoadDispatchVehicleData(DateTime DispatchDate)
        {
            List<InvoiceDispatch> invoices = _orderService.GetVehiclesDAforDate(DispatchDate);
            List<InvoiceDispatch> invoiceDispatches = (from p in invoices
                                                       select p).GroupBy(x => new { x.VehicleNo, x.InvoiceNo })
                                    .Select(g => g.FirstOrDefault()).ToList();
            return Json(new { data = invoiceDispatches }, JsonRequestBehavior.AllowGet);
        }

StoreOrderingDashBoard/Views/Invoice/AddDAForVehicle.cshtml
@{
    ViewBag.Title = "AddDAForVehicle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var VehicleNo = ViewBag.VehicleNo != null ? ViewBag.VehicleNo : "AXBXC";
}
<link href="~/Content/vendors/jquery-ui/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Content/vendors/jquery-ui/jquery-ui.js"></script>
<script src="~/Content/vendors/jquery-ui/jquery-ui.min.js"></script>
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="page-title">
            <div class="title_left">
                <h3>Add DA For Vehicle</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <br />
                        <form id="_DispatchVehicleDateKey" action="@Url.Action("GetDispatchDate","Invoice")">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="Items">Dispatch Date<span class="required">*</span></label>
                                    @Html.AntiForgeryToken()
                                    @(Html.TextBox("DispatchDate", "", new { @class = "form-control", type = "date" }))
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <button class="btn btn-primary" type="button" id="filter">search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        @*<h2>Default Example <small>Users</small></h2>*@
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="loader"></div>
                    <div class="x_content">
                        <form id="_DispatchVehicleDateKey" method="post">
                            @Html.AntiForgeryToken()
                            <table id="vehicle_info_tbl" class="table table-striped table-bordered dataTable no-footer dtr-inline" role="grid" aria-describedby="datatable_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 157px;">Vehicle No</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 115px;">Invoice No</th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 115px;">DA</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </form>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="button" id="savedata">save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var Table;
    $(document).ready(function () {
        $(".loader").hide();
        Table = $('#vehicle_info_tbl').DataTable({
            "order": [[1, "desc"]]
        });

    });
    var selectedStores = [];
    function Jsondate(string) {
        if (string == null || string == undefined)
            return "";
        else
            return new Date(string.match(/\d+/)[0] * 1).toLocaleDateString();
    }
    function StringIsNull(string) {
        if (string == null || string == undefined)
            return "";
        else
            return string;
    }
    $("#filter").click(function () {
        var form = $('#_DispatchVehicleDateKey');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        var DispatchDate = $("#DispatchDate").val();
        if (DispatchDate != "" && DispatchDate != undefined && DispatchDate != null) {
            Table.destroy();
            Table = $("#vehicle_info_tbl").DataTable({
                "ajax": {
                    "url": '@Url.Action("LoadDispatchVehicleData", "Invoice")',
                    "dataType": "JSON",
                    "type": "post",
                    "data": { __RequestVerificationToken: token, DispatchDate: DispatchDate }
                },
                "columns": [
                    {
                        "data": "Vehicle No", "autoWidth": true,
                        render: function (data, type, row, meta) {
                            return '<p id="' + row.Id + '">' + row.VehicleNo + '</p>';
                        }
                    },
                    {
                        "data": "Invoice No", "autoWidth": true,
                        render: function (data, type, row, meta) {
                            return '<p id="' + row.Id + '">' + row.InvoiceNo + '</p>';
                        }
                    },
                    {
                        "data": "DA", "autoWidth": true,
                        render: function (data, type, row, meta) {
                            return '<input type="text"  class="form-control" class="form-control" id="DA' + row.Id + '"/>';
                        }
                    }
                ],
            });
        }
    });
    $("#savedata").click(function () {
        var form = $('#_DispatchVehicleDateKey');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        var tableinfo = Table.page.info();
        var error = false;
        var total = tableinfo.recordsTotal
        var vehicleDisbursementlist = [];
        for (i = 0; i < total; i++) {
            var da = Table.row(i).data();
            var DA = Table.$('input[id=DA' + da.Id + ']').val();
            var vehicleDisbursement = {};
            vehicleDisbursement.VehicleNo = da.VehicleNo;
            vehicleDisbursement.DA = DA;
            vehicleDisbursement.DocNo = da.InvoiceNo;
            //vehicleDisbursement.TransDate = new Date(da.DispatchDate.match(/\d+/)[0] * 1);
            vehicleDisbursement.Error = "";
                        if (vehicleDisbursement.Error != "") {
                            vehicleDisbursementlist = [];
                            error = true;
                            break;
                        }
                        vehicleDisbursementlist.push(vehicleDisbursement);
                    }
        if (error == true) {
                        alert("please solve the errors first.");
                    }
                    else {
                        if (vehicleDisbursementlist.length > 0) {
                            var r = confirm("Are you Sure Want to Upload?");
                            if (r) {
                                $('.loader').show();
                                $('#Uploadbtn').prop('disabled', true);
                                $.ajax({
                                    url: "@Url.Action("SaveDAForVehicle", "invoice")",
                                    type: "POST",
                                    data: {
                                        "vehicleDisbursementList": vehicleDisbursementlist
                                    },
                                    success: function (response) {
                                        if (response) {
                                            alert("List Uploaded Successfully");
                                            window.location = "@Url.Action("UploadVehicleDisbursement", "Order")"
                                        }
                                    },
                                    Error: function (respo) {
                                        alert("unable to upload.");
                                    }
                                });
                            }
                        }
                        else {
                            $('.loader').hide();
                            alert("Please Select Box")
                        }
                    }

    });
</script>

StoreOrderingDashBoard/Views/Invoice/AddDisptchedInformation.cshtml
@using DAL;
@model List<string>
@{
    ViewBag.Title = "AddDisptchedInformation";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<!-- page content -->
<div class="right_col" role="main">
    <div id="">
        <div class="page-title">
            <div class="title_left">
                <h3>Add Disptch Information</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <form id="_XHTDispatchInfokey">
                            <div class="row">
                                <div class="col-md-4">
                                    @Html.AntiForgeryToken()
                                    <label for="SelectedDCs">location <span class="required">*</span></label>
                                    @(Html.DropDownList("SelectedDCs", new SelectList(Model.Select(x => new { Value = x, Text = x }), "Value", "Text"), new { @class = "form-control", required = "required" }))
                                </div>
                                <div class="col-md-4">
                                    <label for="Categories">Date <span class="required">*</span></label>

                                    <div class="form-group">
                                        <div class="input-group date" id="InvoiceDateDRP">
                                            <input type="text" class="form-control" id="InvoiceDate" name="InvoiceDate" />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <button class="btn btn-primary" type="button" id="ViewInvoices" name="ViewInvoices">View Invoices</button>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <table id="tblVehicleInvoices" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Invoice No</th>
                                    <th>Vehicle No</th>
                                    @*<th>Dispatch Date</th>*@
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="x_content">
                        <div class="buttons">
                            <!-- Standard button -->
                            <button type="button" class="btn btn-success btn-sm" id="SaveDisptchInformation">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var Table;
    $(document).ready(function () {
        $('#myDatepicker').datetimepicker();

        $('#InvoiceDateDRP').datetimepicker({
            format: 'YYYY-MM-DD',
            ignoreReadonly: true,
            allowInputToggle: true
        });
        Table = $("#tblVehicleInvoices").DataTable({
            scrollCollapse: true,
        });
        $("#ViewInvoices").on("click", function (event) {
            var $this = $(this);
            var form = $('#_XHTDispatchInfokey');
            var token = $('input[name="__RequestVerificationToken"]', form).val();
            if ($("#SelectedDCs").val() != "" && $("#InvoiceDate").val() != "" && $("#InvoiceDate").val() != "") {
                var SelectedDCs = $("#SelectedDCs").val();
                var InvoiceDate = $("#InvoiceDate").val();
                Table.destroy();
                Table = $("#tblVehicleInvoices").DataTable({
                    "ajax": {
                        "url": '@Url.Action("GetInvoicesforDateDC", "Invoice")',
                        "dataType": "JSON",
                        "type":"post",
                        "data": { SelectedDCs: SelectedDCs, InvoiceDate: InvoiceDate, __RequestVerificationToken: token}
                    },
                    "columns": [
                        {
                            "data": "Invoice No", "autoWidth": true,
                            render: function (data, type, row, meta) {
                                return '<p id="' + row.Id + '">' + row.Invoice_Number + '</p>';
                            }
                        },
                        {
                            "data": "Vehicle No", "autoWidth": true,
                            render: function (data, type, row, meta) {
                                return '<input type="text" class="form-control" id="VehicleNo' + row.Id + '" class="form-control" value="' + StringIsNull( row.VehicleNo )+ '" />';
                            }
                        }
                        //{
                        //    "data": "Dispatch Date", "autoWidth": true,
                        //    render: function (data, type, row, meta) {
                        //        //return '<input type="datetime-local"  class="form-control" id="DispatchDate' + row.Id + '" class="form-control" value="' + StringIsNull( row.DispatchDate )+ '" />';
                        //        return '<div class="input-group date myDatepicker"><input type="text"  id="DispatchDate' + row.Id + '" class="form-control" value="' + DateIsNull(row.DispatchDate) + '" /><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div>'
                        //    }
                        //}
                    ],
                    "initComplete": function (settings, json) {
                        $('.myDatepicker').datetimepicker({
                            format: 'YYYY-MM-DD HH:mm',
                            ignoreReadonly: true,
                            allowInputToggle: true,
                        });
                    }
                });
            }
        });
    });
    function StringIsNull(string) {
        if (string == null || string == undefined)
            return "";
        else
            return string;
    }
    function DateIsNull(string) {
        if (string == null || string == undefined)
            return "";
        else
            return string.tostring('YYYY-MM-DD HH:mm');
    }
</script>
<script>
    $("#SaveDisptchInformation").on("click", function (event) {
        var $this = $(this);
        var rows = Table.rows().data().length;
        var form = $('#_XHTDispatchInfokey');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        var tableinfo = Table.page.info();
        var rowLength = tableinfo.recordsTotal;
        var DisptchInformation = [];
        for (i = 0; i < rowLength; i++) {
            var InvoiceDispatch = {}
            var da = Table.row(i).data();
            var InvoiceNo = da.Invoice_Number;
            var VehicleNo = Table.$('input[id="VehicleNo' + da.Id + '"]').val();
            var DispatchDate = Table.$('input[id="DispatchDate' + da.Id + '"]').val();
            //var index = DispatchDate.indexOf(' ');
            //DispatchDate = DispatchDate.replaceAt(index, 'T') + "Z";
            //DispatchDate = new Date(DispatchDate);
            if (InvoiceNo != "" && VehicleNo != "" && DispatchDate != "") {
                InvoiceDispatch.DispatchDate = DispatchDate;
                InvoiceDispatch.VehicleNo = VehicleNo;
                InvoiceDispatch.InvoiceNo = InvoiceNo;
                DisptchInformation.push(InvoiceDispatch);

            }
            else {
                DisptchInformation = [];
                break;
            }
        }
             if (DisptchInformation.length == 0) {
                    alert("Please fill all fields.");
                }
             else{
                 $this.button('loading');
                 $("#SaveDisptchInformation").prop("disabled", true);
                    $(".loader").show();
                    $.ajax({
                        url: "@Url.Action("SaveDisptchInformation", "Invoice")",
                        type: "post",
                        cache: false,
                        datatype: "json",
                        data: {
                            "DisptchInformation": DisptchInformation,
                            "__RequestVerificationToken": token
                        },
                        success: function (response) {
                            $this.button('reset');
                            $(".loader").hide();
                            $("#SaveDisptchInformation").prop("disabled", false);
                            if (response == 'Unsuccessful') {
                                //OpenModel("AddEditCustomer", "Data not Saved.")
                                alert("Error encountered while saving...");
                            }
                            if (response == 'Successful') {
                                alert("data saved..");
                                Table.clear().draw();
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            $("#SaveDisptchInformation").prop("disabled", false);
                            $(".loader").hide();
                            $this.button('reset');
                            alert("Error encountered while saving...");
                        }
                    })
            }
    });
    String.prototype.replaceAt = function (index, replacement) {
        return this.substr(0, index) + replacement + this.substr(index + replacement.length);
    }
</script>